### ISSUE TITLE
Saving of updated secrets to file system fails at renaming

### ISSUE THREAD

**Issue by OK-UNDP** [undp/azkv#1]
It seems that renaming temporary file fails.
```
Traceback (most recent call last):
  File "/usr/local/bin/azkv", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/azkv/main.py", line 73, in main
    app.run()
  File "/usr/local/lib/python3.7/site-packages/cement/core/foundation.py", line 916, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python3.7/site-packages/cement/ext/ext_argparse.py", line 808, in _dispatch
    return func()
  File "/usr/local/lib/python3.7/site-packages/azkv/controllers/secrets.py", line 331, in save
    file_path_secret_tmp.rename(file_path_secret.name)
  File "/usr/local/lib/python3.7/pathlib.py", line 1329, in rename
    self._accessor.rename(self, target)
OSError: [Errno 18] Invalid cross-device link: '/home/azkv/secret.tmp' -> 'secret'
```
On the surface, it is because of the cross-device link (rename fails when source and target are at different mount points). But further investigation shows that the new file is attempted to be saved in the root file system. Apparently, only the file name and not the full path to the secret file is used.

**Comment by rsaifulin** [comment]
the issue seems to be fixed on AzKV 0.1.0rc6 version
